/// Generated by AssetsRefGenerator on 2020/04/24
class Res {
  static const String login = "images/login.png";
  static const String user = "images/user.png";
  static const String user_bg = "images/user_bg.jpg";
}
